### ISSUE TITLE
Trade in goods: country-by-commodity imports and exports CSV Download Inconsistency 

### ISSUE THREAD

**Issue by RedWalters** [Swirrl/ons-data-export#44]
'Trade in goods: country-by-commodity imports and exports' displays correctly in PMD3 and PMD4 with 15694000 observations, however when the CSV is downloaded - with no filters - in PMD4 only 14799845 observations are outputted.

Unsure if this issue is present in PMD3 as the download currently doesn't work, possible due to the size of the data set.

**Comment by jennet** [comment]
http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-trade-in-goods-catalog-entry

**Comment by jennet** [comment]
line count `wc -l data.csv ` is 14799853

**Comment by RickMoynihan** [comment]
This is expected behaviour at the minute, until we implement this and the accompanying drafter issue https://github.com/Swirrl/muttnik/issues/331

It's just that the dataset has been modified but we don't currently change the database/endpoint modified time in drafter.  Also direct modifications through stardog will not be picked up, if a download of a dataset containing them was ever generated.

The temporary solution is to `rm -rf /var/lib/pmd-data/muttnik/downloads/downloads/live/*` on database updates... or for more localised updates where only the dataset has changed (not codelists, labels etc...) then you may find the hash that contains affected downloads and delete only them.

**Comment by jennet** [comment]
Added step to remove any saved downloads as part of the manual data update process.

**Comment by jennet** [comment]
Download checked as having the correct number of lines
